method: ddim
model_type: SDXL
scheduler_type: DDIM
seed: 7865
negative_prompt: null
num_inference_steps: 50
num_inversion_steps: 50
inversion_max_step: 1.0
guidance_scale: 7.5
inversion_guidance_scale: 1.0
reconstruction_guidance_scale: 1.0
random_image_guidance_scale: 5.0
inference_use_ipa: true
inversion_use_ipa: true
inference_ipa_scale: 0.4
inversion_ipa_scale: 0.4
saturation_removal_ipa_scale: 0.4
num_gd_steps: 0
gd_step_size: 0.001
optimization_start: 0
normalize: false
random_inference_times: 0
remove_cfg_saturation: false
